### ISSUE TITLE
Ground truth cofficients format

### ISSUE THREAD

**Issue by E1eMenta** [mvirgo/MLND-Capstone#12]
How can I draw lines from "Images with coefficient labels" dataset on image?

**Comment by mvirgo** [comment]
You'll want to check out the [early_steps branch](https://github.com/mvirgo/MLND-Capstone/tree/early_steps), especially the `make_labels.py` file. It won't be exactly what you need, but you can also check out my older [Advanced Lane Lines repository](https://github.com/mvirgo/Advanced-Lane-Lines) that goes through the remaining steps to combine the lane detection onto the original image.
