### ISSUE TITLE
Dataset and Labels

### ISSUE THREAD

**Issue by mrinaliniP** [mvirgo/MLND-Capstone#14]
Hi,
Iam facing following issues:

1.I am not able to open the full_CNN_train.p and CNN_label.p in Matlab.
2.How can I train  and label my own dataset using this code?

Please can you guide where I am doing wrong

**Comment by ShawnXsw** [comment]
@mrinaliniP try to read early_steps: undistort_and_transform.py

**Comment by Neha-swan** [comment]
Where do i find this dataset

**Comment by mvirgo** [comment]
I'm not sure whether the pickle files are formatted to easily open in Matlab or not, unfortunately. The project is only supported in Python. For Neha, these are linked on the ReadMe.
