### ISSUE TITLE
Queries regarding making my own dataset

### ISSUE THREAD

**Issue by vineeth2309** [mvirgo/MLND-Capstone#16]
1) How did you create the labels file? I have created a program to output the coefficients of the lane fit, but i am not sure how to append them to a labels file. Are they just simply added to a labels.p file or do we have to append the image name and then the coefficients.
2) Also were the coefficients of the lane calculated from the resized 80*160 image or on the normal image
 size.

**Comment by mmudeshi077** [comment]
@vineeth2309 how are creating you own dataset. I mean are you able to see the .p files what is inside it.

**Comment by mvirgo** [comment]
You can check the [early_steps branch](https://github.com/mvirgo/MLND-Capstone/tree/early_steps), and related `make_labels.py` file, for an example of this - you just dump it to a pickle file (you might also use a hdf5 file instead).

The coefficients are from the normal image size.
