### ISSUE TITLE
how to modify .p file ?

### ISSUE THREAD

**Issue by mmudeshi077** [mvirgo/MLND-Capstone#17]
how i can modify .p file acording to my need.

**Comment by hising96** [comment]
how to i convert my images and label datset folder to .p extension
thanks in advance

**Comment by mvirgo** [comment]
Hi all - these are pickle files, so check out [here](https://wiki.python.org/moin/UsingPickle) to use them. My provided datasets are lists of images, so you can modify it by as you would normally modify images within a list.
