### ISSUE TITLE
Explanation about the neural network architecture

### ISSUE THREAD

**Issue by hxlee309** [mvirgo/MLND-Capstone#18]
Hi,

Is there any related paper or documentation for the neural network architecture you build? If yes, please share the file or the link with me.

Thanks

**Comment by mvirgo** [comment]
There is both the [Capstone Report](https://github.com/mvirgo/MLND-Capstone/blob/master/MLND%20Capstone%20Project%20Report.pdf) as well as related [Medium post](https://towardsdatascience.com/lane-detection-with-deep-learning-part-2-3ba559b5c5af).
