### ISSUE TITLE
What is the hardware requirement for this project?

### ISSUE THREAD

**Issue by kvnptl** [mvirgo/MLND-Capstone#24]
Very well documented project. Thanks a lot for this detail. You have mentioned all about software. I have few doubts regarding hardware requirement for this project?

1. Which GPU/Cloud platform you have used for this project? 
2. Is it possible to run this neural network on Laptop with 4GB RAM and 240GB SSD (intel i3)?
3. How much time did you get to train all images?

**Comment by mrronjt** [comment]
I think you do need a GPU to train a neural network.
Try Google Colab, which is a free online GPU from Google.

**Comment by mvirgo** [comment]
The above is correct. I used a GTX 1060 at the time; unfortunately I don't remember exactly on training time, but it wasn't that extensive as the neural network I used is not super deep/complex. You might potentially need more RAM based on the default code I provide here, as I wasn't using a very smart method for image & memory management (it pretty much loads all images up front).
