### ISSUE TITLE
What method of training did you use for the Neural Network?

### ISSUE THREAD

**Issue by CCLDArjun** [mvirgo/MLND-Capstone#25]

**Comment by mvirgo** [comment]
All training settings are contained in [fully_conv_NN.py](https://github.com/mvirgo/MLND-Capstone/blob/master/fully_conv_NN.py). Note that I also have a [couple Medium posts](https://towardsdatascience.com/lane-detection-with-deep-learning-part-1-9e096f3320b7) on my overall process, if interested.
