### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = 'full_CNN_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0) 

### ISSUE THREAD

**Issue by mduccc** [mvirgo/MLND-Capstone#26]
I got an error after i had run `python3 MLND-Capstone/draw_detected_lanes.py`:

> Traceback (most recent call last):
>   File "MLND-Capstone/draw_detected_lanes.py", line 9, in <module>
>     model = load_model('full_CNN_model.h5')
>   File "/usr/lib/python3.7/site-packages/keras/engine/saving.py", line 458, in load_wrapper
>     return load_function(*args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/keras/engine/saving.py", line 549, in load_model
>     with H5Dict(filepath, mode='r') as h5dict:
>   File "/usr/lib/python3.7/site-packages/keras/utils/io_utils.py", line 191, in __init__
>     self.data = h5py.File(path, mode=mode)
>   File "/usr/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
>     swmr=swmr)
>   File "/usr/lib/python3.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
>     fid = h5f.open(name, flags, fapl=fapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 85, in h5py.h5f.open
> OSError: Unable to open file (unable to open file: name = 'full_CNN_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by mvirgo** [comment]
This is just saying you are missing the model file. You can download it from the ReadMe.

**Comment by mduccc** [comment]
> This is just saying you are missing the model file. You can download it from the ReadMe.

I had model file.
I just fix like:
`model = load_model(r'/home/mducc/Projects/sefl car/MLND-Capstone/model.h5')`
