### ISSUE TITLE
labels and output

### ISSUE THREAD

**Issue by imaneelhg** [mvirgo/MLND-Capstone#27]
how to make labels without that redrawn lanes ? or how to get those redrawn lanes
can we change the final output to be a convolution and not a deconv and what should the output be

**Comment by mvirgo** [comment]
This project uses a fully convolutional neural network, so the only possible output, as labeled, is an identification of the lane within the lane lines. It is not set up to only do the lines.

**Comment by mvirgo** [comment]
Closing out since no further comments.
