### ISSUE TITLE
what are those numbers in labels

### ISSUE THREAD

**Issue by imaneelhg** [mvirgo/MLND-Capstone#28]
can someone plz explain the outputs of the cnn what is that array

**Comment by mvirgo** [comment]
The array is the resulting "map" of the lane. Basically, it will be near zero if it doesn't think a given pixel is part of the array, and near one if it thinks it is part of the lane. It is a fully convolutional neural network that is predicting the "class" of each and every pixel (in this case, just lane or not lane).

**Comment by mvirgo** [comment]
Closing out since no further comments.
