### ISSUE TITLE
the way to label data

### ISSUE THREAD

**Issue by twmht** [mvirgo/MLND-Capstone#3]
Hi @mvirgo ,

I am curios how you make the label like below,

![image](https://user-images.githubusercontent.com/1567200/27073849-d4d0eac0-5057-11e7-9253-f4485bd0501c.png)

I have read the report you post here.

in the `Algorithms and Techniques` section, you said

`Next, I must process the images for
use in making labels, for which I will use the same techniques I previously used in my computer
vision-based model`

But I can't find the `previous model` you used.

In the `reflection` part, you said

```
I then created six coefficient labels, three each for both lane lines. Next, I created a program to
make those labels into re-drawn lanes
```
then I look into `make_labels.py`, you define `load_drawn_images`,

```
def load_drawn_images():
    """Load re-drawn lane image locations"""
    drawn_image_locs = glob.glob('draw/*.jpg')
    sort_drawn_image_locs = sorted(drawn_image_locs, key=natural_key)
    return sort_drawn_image_locs    
```

I don't know how to make `re-drawn` images.

Can you show an example about labeling the image step by step and which python files you used?

thanks

**Comment by mvirgo** [comment]
The `make_labels.py` file is where you need to be; I just re-drew over the original lines in red to make them clearer. If you change the color thresholds in here to more closely match normal road conditions you can get what you need.

You can also check out [Advanced Lane Lines](https://github.com/mvirgo/Advanced-Lane-Lines) for examples of normal thresholds, although do note I think that still uses the old method that doesn't work with curves as well.
