### ISSUE TITLE
How have you made file full_CNN_train.p and full_CNN_labels.p using advanced lane generation?Which 3 parameters for left or right lanes are?

### ISSUE THREAD

**Issue by Rhutus** [mvirgo/MLND-Capstone#30]

**Comment by mvirgo** [comment]
My apologies on not getting back to you on this. Those pickle files do not contain the three parameters, as they contain values for whether or not a given pixel is part of the lane or not, as part of a fully convolutional network. The `coeffs_train.p` and `coeffs_labels.p` files also linked in the README contain the parameters if you were wanting to fit polynomials to the lane lines.

**Comment by Bersion** [comment]
How can I process my data set into a file like this？

**Comment by mvirgo** [comment]
@Bersion Pickle files are detailed [here](https://docs.python.org/3/library/pickle.html), or you can also use something like [HDF5](https://docs.h5py.org/en/stable/), which I later found to actually be a little easier to work with (and I believe it's faster). At some point I should probably change over the dataset...

**Comment by mvirgo** [comment]
Closing since no further comments.
