### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by raflialhamdi** [mvirgo/MLND-Capstone#35]
when i run the check_labels.py in line 36 the issue is ValueError: operands could not be broadcast together with shapes and one more question what is list index out of range. Can you help me pls?

**Comment by mvirgo** [comment]
My apologies on the wait. I would need the full error message, most likely, as it isn't clear from this what might be going on. If it's line 36 throwing an error, my guess is that the `other` image is coming in with a different shape than expected, but it isn't clear from just this if that is the case. A lot of that older file is likely specific to the exact dataset I was using, so if you're using something else, you would likely need to customize the code further.

**Comment by mvirgo** [comment]
Closing since no further comments.
