### ISSUE TITLE
how i use the .p dataset?

### ISSUE THREAD

**Issue by zhaohuaqing1993** [mvirgo/MLND-Capstone#4]
the .p dataset is just like a .jpg?how can i see this picture?thanks !

**Comment by mvirgo** [comment]
The .p files are pickle files - you could load them as such:
`import pickle`
`train_images = pickle.load(open("full_CNN_train.p", "rb" ))`
Now if you wanted to look at the first image in the training set:
`import matplotlib.pyplot as plt`
`plt.imshow(train_images[0])`
You may also need to use `plt.show()` after the above line for the image to actually come up.
