### ISSUE TITLE
cv2.addWeighted(image, 1, lane_image, 1, 0)

### ISSUE THREAD

**Issue by darshineebungsy** [mvirgo/MLND-Capstone#41]
Hii
I tried implementating the code with another video and got this error.
![Screenshot 2022-04-18 204546](https://user-images.githubusercontent.com/81421709/163842010-a43aa726-1783-46ff-b644-d82737700dee.png)

**Comment by gm24med** [comment]
can you tell me how did you solve this problem ?

**Comment by nile-sosa** [comment]
Make sure the input video resolution is greater than 720p, that fixed the issue for me
