### ISSUE TITLE
No matching ActionLib Distribution

### ISSUE THREAD

**Issue by corlinp** [mvirgo/MLND-Capstone#8]
When I run `conda env create -f lane_environment.yml` I get the following error: `Collecting actionlib==1.11.7 Could not find a version that satisfies the requirement actionlib==1.11.7`

If actionlib is required for this, can you maybe update the environment file with another compatible version?

Thanks

**Comment by shriyash555** [comment]
I too getting the same issue

**Comment by mvirgo** [comment]
You should be able to remove actionlib from the environment file without issue - it's actually related to ROS. If it still isn't working for you, I'll try to look into cutting down the environment file to just the bare necessities over the next couple of weeks.

**Comment by JerryAIwei** [comment]
I get the same problem, some else file also could not be found,. I am trying to work on ubuntu
--update--
So just remove those for ROS, and everything works well.

**Comment by kanhanlu** [comment]
@JerryAIwei 
I got the same and found lot of package cannot be found. Could you list those packages you removed?

**Comment by mvirgo** [comment]
I'm going to try at some point to narrow down the environment file to just what is truly need to run the code as is, so hopefully that will (years later :) ) help with this.

**Comment by mvirgo** [comment]
Hi all! Finally closing this one out as I've vastly simplified the environment file, and it should now be much easier to fix any issues that arise - it now only includes the seven primary libraries used in the code.
